# brew bundle

# taps (casks at bottom)
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'trinitronx/truecrypt'

# brews
brew 'ack'
brew 'boost'
brew 'cairo'
brew 'capnp'
brew 'cmake'
brew 'curl'
brew 'f3'
brew 'ffmpeg', args: ['with-libvpx', 'with-libvorbis']
brew 'flac'
brew 'freetype'
brew 'gdbm'
brew 'gist'
brew 'git'
brew 'gpg'
brew 'hub'
brew 'imagemagick'
brew 'jpeg'
brew 'libogg'
brew 'libpng'
brew 'libtiff'
brew 'libtool'
brew 'libvorbis'
brew 'libyaml'
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'p7zip'
brew 'pcre'
brew 'pkg-config'
brew 'postgres'
brew 'python'
brew 'python@2'
brew 'readline'
brew 'rename'
brew 'ruby'
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'xz'
brew 'zsh'

# casks (taps at top)
cask 'xquartz'
cask 'atom'
cask 'dbeaver-community'
cask 'deluge'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'inkscape'
cask 'iterm2'
cask 'java'
cask 'sketch'
cask 'spectacle'
cask 'truecrypt'
cask 'vlc'

