#
# brew bundle
# brew bundle cleanup  # list. --force to remove.
#

### taps (casks at bottom)
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'koekeishiya/formulae'
tap 'superfly/tap'

### brews
brew 'ack'
brew 'aspell'
brew 'autoconf'
brew 'autojump'
brew 'base64'
brew 'bison'
brew 'boost'
brew 'cmake'
brew 'curl'
brew 'ffmpeg', args: ['with-libvpx', 'with-libvorbis']
brew 'flac'
brew 'flex'
brew 'flyctl'
brew 'freetype'
brew 'fzf'
brew 'gdb'
brew 'gdbm'
brew 'gist'
brew 'git'
brew 'gpg'
brew 'hub'
brew 'id3lib'
brew 'imagemagick'
brew 'jless'
brew 'jpeg'
brew 'jq'
brew 'libogg'
brew 'libpng'
brew 'libtiff'
brew 'libtool'
brew 'libvorbis'
brew 'libyaml'
brew 'llvm'
brew 'neovim'
brew 'node'
brew 'openssl'
brew 'p7zip'
brew 'pcre'
brew 'pgcli'
brew 'pkg-config'
brew 'postgres'
brew 'python'
brew 'readline'
brew 'rename'
brew 'restic'
brew 'tree'
brew 'up'
brew 'wget'
brew 'xz'
brew 'yabai'
brew 'yamllint'
brew 'zlib'
brew 'zsh'

### casks (taps at top)
cask 'authy'
cask 'backblaze'
cask 'balenaetcher'
cask 'dbeaver-community'
cask 'deluge'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'lastpass'
cask 'rar'
cask 'sketch'
cask 'vscodium'
cask 'vlc'
cask 'zoom'

